### ISSUE TITLE
Parabens! Belo trabalho

### ISSUE THREAD

**Issue by guilhermerodrigues680** [marcos-tulio/8-bit-computer-emulator#4]
---

**Comment by marcos-tulio** [comment]
Vlw, Seu Guilherme! Ainda não acabai de documentar todo ele.

Você chegou a rodar? O legal é ficar programando ele hahaha. 

Vou deixar aqui um algoritmo de soma para você brincar -- basta digitar os comandos no terminal interno.

Aqui é a parte de instrução:
> 8-bit << ram load addr 0 val b0001 1110
> 8-bit << ram load addr 1 val b0100 1111
> 8-bit << ram load addr 2 val b1110 0000
> 8-bit << ram load addr 3 val b1111 0000

parte de dados (neste caso vai somar 45 com 55):
> 8-bit << ram load addr b1110 val 45
> 8-bit << ram load addr b1111 val 55 

Para rodar (o resultado aparece no registrador de saída):
> 8-bit << run

Ou senão, caso queira vou deixar o mesmo algoritmo em [Assembly](https://github.com/marcos-tulio/8-bit-computer-emulator/files/4377723/soma.zip), pode carrega-lo usando o seguinte comando:
> 8-bit << asm

Para inserir os dados (o mesmo que na forma anterior):
> 8-bit << ram load addr b1110 val 45
> 8-bit << ram load addr b1111 val 55 

Para rodar:
> 8-bit << run

Por fim, use este para parar o processo:
> 8-bit << stop

Forte abraço, meu parceiro!

Obs.: Vai notar o alto processamento ao executar. Fiz desta forma para ter o máximo de fidelidade de um sistema físico -- manter os tempos o mais preciso possível, principalmente em altas frequências.
